### ISSUE TITLE
physical-quantities

### ISSUE THREAD

**Issue by Symbolics** [Shinmera/LASS#13]
Is this library easily replaced or removed? Physical-quantities has a restricted license that makes it unsuitable for project work. Parseq does too, but that could be replaced by esrap.

**Comment by Shinmera** [comment]
Very, In fact I've just pushed a fix to remove it again, since it's only caused problems for me so far.

**Comment by Symbolics** [comment]
That was quick, thanks. Is `parseq` equally simple?

**Comment by Shinmera** [comment]
That was part of the physical quantities thing.
