### ISSUE TITLE
:hover pseudo-selector subblock not expanded correctly (space inserted)

### ISSUE THREAD

**Issue by pchodgson** [Shinmera/LASS#18]
I ran into a problem where the code
`(lass:compile-and-write 
  '(.time-slot
	 :border-top 1px dashed black
	 :font-size small
	 :height 20px
     (:hover :background-color lightgray)))`

outputs 
`".time-slot {
    border-top: 1px dashed black;
    font-size: small;
    height: 20px;
}
.time-slot :hover{
    background-color: lightgray;
}"
`
which looks alright, but there is space between '.time-slot' and ':hover'  which makes this invalid CSS, and the browser will not understand it. 

I'm note sure if this is a bug or just a missing feature/divergent expectation, because the default behavior for subblocks would be selecting descendant elements of the primary/antecedent specifier, so the space is usually necessary.

I made this hyper-hacky change in #'compile-constraint to get the desired behavior:
`                     do (push (list :constraint :combine (if (string= ":hover" (third arg)) "" " ") func arg) result))`

**Comment by Shinmera** [comment]
This is expected behaviour. Sub blocks will add a space. What you want is the same as #5, some way to elide the space and instead combine with the parent selector.

The typical way to do this currently without the new feature is to do `(.time-slot ...) ((:and .time-slot :hover) ...)`
