### ISSUE TITLE
CSS4 pseudo-classes

### ISSUE THREAD

**Issue by aartaka** [Shinmera/LASS#19]
There's a bunch of new pseudo-classes in CSS4, and these are often vital for proper page CSS. Like:
- https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes
- https://drafts.csswg.org/selectors/#logical-combination

Would be nice to have them in LASS, to not resort to CSS syntax for new features 😃

**Comment by boogsbunny** [comment]
Agreed! Would you consider adding those @Shinmera?
