### ISSUE TITLE
Add single string value for box-shadow property

### ISSUE THREAD

**Issue by rubens-schmitz** [Shinmera/LASS#8]
In all other properties you can pass a single string with multiple values separated by space:
`:border "1px solid #1d2f2f"`
But for box-shadow you have to pass one string for each value:
`:box-shadow "1px" "1px" "10px" "2px" "#3a5f5f"`

**Comment by Shinmera** [comment]
why strings at all? just write `:box-shadow 1px solid (hex 1d2f2f)`

**Comment by rubens-schmitz** [comment]
Nice :)
